workflows:
  react-native-android:
    name: React Native Android AAB Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: 'nuh'
      node: latest
      java: 17
    cache:
      cache_paths:
        - node_modules
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Install dependencies
        script: |
          npm ci --prefer-offline --no-audit --no-fund

      - name: Prepare Android signing
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo "Decoding keystore..."
            echo "$CM_KEYSTORE" | base64 --decode > /tmp/release.keystore

            echo "Writing keystore.properties..."
            rm -f android/keystore.properties
            echo "storePassword=$CM_KEYSTORE_PASSWORD" >> android/keystore.properties
            echo "keyPassword=$CM_KEY_PASSWORD" >> android/keystore.properties
            echo "keyAlias=$CM_KEY_ALIAS" >> android/keystore.properties
            echo "storeFile=/tmp/release.keystore" >> android/keystore.properties
          else
            echo "⚠️ Warning: CM_KEYSTORE not found. The AAB will be unsigned."
          fi

      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean

      - name: Build Release AAB
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/mapping.txt
      - android/app/build/outputs/**/mapping.txt.gz

    publishing:
      email:
        recipients:
          - shubashisroy360@gmail.com
