workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: 'nuh' # your app package name
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean
      - name: Build Release APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - shubashisroy360@gmail.com
